apiVersion: 1

# Automatically provision the Prometheus datasource for Cerberus dashboards

datasources:
  - name: Cerberus Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET
      timeInterval: 5s
    isDefault: true
    editable: false
